let superHeroName = 'Batman';
let name = 'Bruce Wayne';
let fly = false;
let hasBatmobile = true;
let life = 40;
let freeTime = null;
console.log('superHeroName:', superHeroName);
console.log('name:', name);
console.log('fly:', fly);
console.log('hasBatmobile:', hasBatmobile);
console.log('life:', life);
console.log('freeTime:', freeTime);
console.log('superHeroName:', typeof superHeroName);
console.log('name:', typeof name);
console.log('fly:', typeof fly);
console.log('hasBatmobile:', typeof hasBatmobile);
console.log('life:', typeof life);
console.log('freeTime:', typeof freeTime);
