const firstSide=10;
const secondSide=20;
const thirdSide=5;
const perimeterOfaTriangle= firstSide + secondSide + thirdSide;
console.log('perimeter of a triangle:', perimeterOfaTriangle );
console.log('Sides length:');
console.log(' First side:', firstSide); 
console.log(' Second side:',secondSide);
console.log(' Third side:',thirdSide);
console.log('Perimeter of a triangle is a sum of the three sides');