var firstname = 'Marcia';
var lastname = 'Cardoso';
var age = 41;
var dateOfBirth = '07/08/1976';
var address = '26 summers place';
console.log('firstname:', firstname);
console.log('lastname:', lastname);
console.log('age:',age);  
console.log('dateOfBirth:', dateOfBirth);
console.log('address:', address);