var firstname = 'Marcia';
var lastname = 'Cardoso';
var age = 41;
var dateOfBirth = '07/08/1976';
var address = '26 summers place';
console.log(firstname);
console.log(lastname);
console.log(age);
console.log(dateOfBirth);
console.log(address);
